### ISSUE TITLE
change about page layout to come from a single yaml file

### ISSUE THREAD

**Issue by olevett** [sedostheatre/sedos.co.uk#332]
with links to other pages

```yaml
- title: something something
  image: /path/to/asset.png
  link: /path/to/page
  row: 2
  column: 1
- ...
```

and remove the similar config from about sections as well
