### ISSUE TITLE
netlify - venues config

### ISSUE THREAD

**Issue by olevett** [sedostheatre/sedos.co.uk#350]
- add venues configuration
- move shows/events/regular events to use new venues collection (see show details for example)

Single file, of the format
```yml
venues
  - url: /venues/bridewell
    name: The Bridewell
    key: bridewell
  - ...
```
